[package]
name = "slice"
authors = ["bumbledbees"]
description = "grabs an arbitrary size slice out of a file"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["cargo", "derive"] }
